"""Stateful connection manager for the Meshtastic TCP interface.

Hermes tool handlers are stateless functions, but a Meshtastic link is a
long-lived object with a background receive thread. This module owns a single
process-wide connection plus the observer that feeds the knowledge base.

`meshtastic` is a declared (hard) dependency, normally installed automatically by
pip. It is still imported lazily inside `connect()` so a bare directory-drop
install (no pip step) can load — and its KB-query tools can run — even when the
radio stack happens to be missing.
"""

from __future__ import annotations

import logging
import os
import sys
import threading
from typing import Any

logger = logging.getLogger(__name__)

DEFAULT_TCP_PORT = 4403

# Three-state connection reporting ------------------------------------------------
# A bare "connected: false" cannot tell a node that is still booting apart from a
# configuration that will never work. These are the three states we report:
#
#   connected     — a live, working interface.
#   connecting    — the supervisor is running and still retrying at full rate; the
#                   consecutive-failure threshold has not been reached. A TCP
#                   "connection refused" while a node boots lands here, not in
#                   disconnected: it is expected, not an error.
#   disconnected  — we are not usefully trying any more: the user explicitly
#                   disconnected, we never tried, or N consecutive attempts failed
#                   and the supervisor has dropped to the slow retry cadence.
STATE_CONNECTED = "connected"
STATE_CONNECTING = "connecting"
STATE_DISCONNECTED = "disconnected"

DEFAULT_FAILURE_THRESHOLD = 10
DEFAULT_SLOW_RETRY_SECONDS = 300.0


def _env_number(name: str, default, cast):
    """Read a positive numeric env var, falling back to *default* when unusable."""
    raw = os.environ.get(name)
    if raw is None or not raw.strip():
        return default
    try:
        value = cast(raw.strip())
    except (TypeError, ValueError):
        logger.warning("%s=%r is not a number — using default %s", name, raw, default)
        return default
    if value <= 0:
        logger.warning("%s=%r must be > 0 — using default %s", name, raw, default)
        return default
    return value


def failure_threshold() -> int:
    """Consecutive failed connect attempts before the state becomes `disconnected`."""
    return _env_number("MESHTASTIC_FAILURE_THRESHOLD", DEFAULT_FAILURE_THRESHOLD, int)


def slow_retry_seconds() -> float:
    """Retry interval used once the failure threshold has been exceeded."""
    return _env_number("MESHTASTIC_SLOW_RETRY_SECONDS", DEFAULT_SLOW_RETRY_SECONDS, float)


def enable_debug_logging() -> bool:
    """If MESHTASTIC_DEBUG is truthy, route this plugin's loggers to stderr at DEBUG.

    Self-contained on purpose: the Hermes gateway logs at WARNING unless started with
    ``-v``/``-vv`` (and its systemd unit is regenerated by ``hermes gateway`` commands),
    so this gives a plugin-owned switch whose output reaches ``journalctl`` regardless.
    Idempotent across repeated plugin registration.
    """
    if os.environ.get("MESHTASTIC_DEBUG", "").strip().lower() not in {"1", "true", "yes", "on"}:
        return False

    # Hermes loads plugins under a mangled namespace (e.g.
    # `hermes_plugins.<key>__meshtastic_platform.adapter`), so we can't target our
    # logger names directly. Attach a stderr handler to the ROOT logger that only
    # emits meshtastic records, and lower the root level so DEBUG/INFO propagate to
    # it. The gateway's own handler keeps its WARNING level, so nothing else is noisier.
    # Match THIS plugin's loggers only (real names or Hermes' mangled
    # `hermes_plugins.<key>__meshtastic_platform.adapter` form) — but NOT the noisy
    # `meshtastic.*` radio library logger.
    root = logging.getLogger()
    # If the gateway already has a root handler that emits WARNING+, only take records
    # BELOW WARNING here so WARNING/ERROR aren't logged twice. In standalone use (no
    # such handler) we emit everything.
    _other_warn = any(
        h.level <= logging.WARNING for h in root.handlers if not getattr(h, "_mesh_debug", False)
    )

    class _PluginOnly(logging.Filter):
        def filter(self, record: logging.LogRecord) -> bool:
            n = record.name
            if "meshtastic_platform" not in n and "meshtastic_hermes" not in n:
                return False
            if _other_warn and record.levelno >= logging.WARNING:
                return False  # let the existing root handler emit it (no duplicate)
            return True

    if not any(getattr(h, "_mesh_debug", False) for h in root.handlers):
        handler = logging.StreamHandler(sys.stderr)
        handler.setLevel(logging.DEBUG)
        handler.setFormatter(logging.Formatter("%(levelname)s %(name)s: %(message)s"))
        handler.addFilter(_PluginOnly())
        handler._mesh_debug = True  # type: ignore[attr-defined]  # marker for dedup
        root.addHandler(handler)
    if root.level > logging.DEBUG or root.level == logging.NOTSET:
        root.setLevel(logging.DEBUG)
    # Lowering root to DEBUG would otherwise unleash the radio library's very verbose
    # per-packet DEBUG; keep it at WARNING so only our plugin's logs show.
    logging.getLogger("meshtastic").setLevel(logging.WARNING)
    return True


class MeshtasticUnavailable(RuntimeError):
    """Raised when the optional `meshtastic` package is not importable."""


def _import_meshtastic():
    try:
        import meshtastic  # noqa: F401
        import meshtastic.tcp_interface  # noqa: F401

        return meshtastic
    except ImportError as exc:  # pragma: no cover - exercised only without extra
        raise MeshtasticUnavailable(
            "The 'meshtastic' package is not installed in Hermes' Python environment. "
            "Install the 'meshtastic' package there with pip "
            "(normally pulled in automatically when this plugin is installed with pip)."
        ) from exc


class ConnectionManager:
    """Owns the active TCPInterface and wires the receive observer."""

    def __init__(self) -> None:
        self._iface: Any = None
        self._host: str | None = None
        self._port: int = DEFAULT_TCP_PORT
        self._lock = threading.Lock()
        self._observer = None  # set lazily to avoid import cycle
        # Supervisor: keep the link up while connection is desired, so the gateway
        # keeps RECEIVING across drops without anyone re-calling connect().
        self._want_connected = False
        self._stop = threading.Event()
        self._supervisor: threading.Thread | None = None
        # Interfaces that lost their connection but haven't been closed yet. We close
        # them from a safe thread (not the library's reader thread) to cancel their
        # heartbeat timers, which otherwise keep writing to dead sockets (BrokenPipe).
        self._stale_ifaces: list[Any] = []
        # Three-state bookkeeping. Guarded by _lock (the supervisor thread writes
        # these while status() reads them from a caller's thread).
        self._consecutive_failures = 0
        self._slow_retry = False
        self._hard_error: str | None = None

    # ------------------------------------------------------------------

    def connect(self, host: str, port: int = DEFAULT_TCP_PORT) -> dict[str, Any]:
        """Open a TCP connection to `host` and subscribe the observer.

        Idempotent-ish: an existing connection is closed first.
        """
        self._host = host
        self._port = port
        self._want_connected = True
        self._stop.clear()
        # A fresh connect() is a fresh attempt: clear any previous slow-retry/hard
        # state so an explicit reconnect starts back in `connecting`.
        with self._lock:
            self._consecutive_failures = 0
            self._slow_retry = False
            self._hard_error = None
        try:
            self._open()
        except MeshtasticUnavailable as exc:
            # HARD failure: the radio library itself is missing. No amount of retrying
            # fixes that, so report `disconnected` rather than sitting in `connecting`.
            with self._lock:
                self._hard_error = str(exc)
            raise  # radio lib genuinely missing — no point supervising
        except Exception as exc:
            # SOFT failure (connection refused, timeout, DNS not resolvable yet): the
            # node may simply be booting. Don't fail hard, let the supervisor retry.
            self._record_failure()
            logger.warning(
                "Initial Meshtastic connect to %s failed: %s (supervisor will retry)", host, exc
            )
        else:
            self._record_success()
        self._ensure_supervisor()
        return self.status()

    # -- failure accounting -------------------------------------------------

    def _record_success(self) -> None:
        """A successful open: reset the consecutive-failure counter and cadence."""
        with self._lock:
            was_slow = self._slow_retry
            self._consecutive_failures = 0
            self._slow_retry = False
            self._hard_error = None
        if was_slow:
            logger.info("Meshtastic link recovered — leaving slow-retry mode")

    def _record_failure(self) -> int:
        """A failed open. Returns the new consecutive-failure count."""
        threshold = failure_threshold()
        with self._lock:
            self._consecutive_failures += 1
            count = self._consecutive_failures
            entering_slow = count >= threshold and not self._slow_retry
            if entering_slow:
                self._slow_retry = True
        if entering_slow:
            logger.warning(
                "Meshtastic connect to %s failed %d consecutive times (threshold %d) — "
                "reporting state=disconnected and backing off to a slow retry every %.0fs. "
                "Retrying continues in the background so the node can still self-heal.",
                self._host,
                count,
                threshold,
                slow_retry_seconds(),
            )
        return count

    def _open(self) -> None:
        """(Re)open the interface and wire subscriptions. Raises on failure."""
        mesh = _import_meshtastic()
        from pubsub import pub

        from . import observer as _observer

        with self._lock:
            # Always clean up first — even after a loss left _iface=None, stale pubsub
            # subscriptions may linger and must be dropped before re-subscribing.
            self._close_locked()

            iface = mesh.tcp_interface.TCPInterface(self._host, portNumber=self._port)
            self._iface = iface

            # Subscribe to the parent topic to capture ALL packet types, including
            # encrypted PRIVATE_APP traffic on channels we cannot read. (pubsub topics
            # are global, so the observer keeps receiving across reconnects.)
            self._observer = _observer.get_observer()
            pub.subscribe(self._observer.on_receive, "meshtastic.receive")
            pub.subscribe(self._on_connection_lost, "meshtastic.connection.lost")

    def _ensure_supervisor(self) -> None:
        if self._supervisor and self._supervisor.is_alive():
            return
        self._supervisor = threading.Thread(
            target=self._supervise, name="meshtastic-reconnect", daemon=True
        )
        self._supervisor.start()

    def _supervise(self) -> None:
        """Keep the link up while connection is desired (reconnect with backoff)."""
        backoff = 2
        while self._want_connected and not self._stop.is_set():
            if self._iface is None:
                try:
                    self._open()
                except Exception as exc:
                    self._record_failure()
                    # Once past the threshold we report `disconnected` but keep
                    # retrying — slowly — so the link still self-heals unattended.
                    if self._slow_retry:
                        wait = slow_retry_seconds()
                    else:
                        wait = backoff
                        backoff = min(backoff * 2, 60)
                    logger.warning("Meshtastic reconnect failed: %s (retry in %ss)", exc, wait)
                    self._stop.wait(wait)
                    continue
                else:
                    self._record_success()
                    logger.info("Meshtastic reconnected to %s", self._host)
                    backoff = 2
            self._stop.wait(3)  # poll for drops

    def _on_connection_lost(self, interface=None) -> None:
        # Called on the library's reader thread — do NOT close here (close() may join
        # the very thread we're on). Stash the dead interface for the supervisor/next
        # _open() to close safely.
        with self._lock:
            # Honor WHICH interface died. After a drop+reconnect, an *old* iface's
            # reader can still publish a late connection.lost; without this identity
            # check it would null the healthy NEW _iface and trigger a spurious
            # reconnect loop. Only the current interface losing means we're down.
            if (
                interface is not None
                and self._iface is not None
                and interface is not self._iface
            ):
                if interface not in self._stale_ifaces:
                    self._stale_ifaces.append(interface)
                logger.debug(
                    "Ignoring connection.lost from a stale interface — current link is healthy"
                )
                return
            old = interface or self._iface
            if old is not None and old not in self._stale_ifaces:
                self._stale_ifaces.append(old)
            self._iface = None
        logger.warning("Meshtastic connection lost — supervisor will reconnect")

    def disconnect(self) -> dict[str, Any]:
        # Stop the supervisor first so it doesn't immediately reconnect.
        self._want_connected = False
        self._stop.set()
        with self._lock:
            self._close_locked()
            # An explicit disconnect is not a retry state: report `disconnected`.
            self._consecutive_failures = 0
            self._slow_retry = False
            self._hard_error = None
        return {"connected": False, "state": STATE_DISCONNECTED}

    def _close_locked(self) -> None:
        try:
            from pubsub import pub

            if self._observer is not None:
                pub.unsubscribe(self._observer.on_receive, "meshtastic.receive")
            # Always drop the loss subscription too, so reconnects don't accumulate
            # duplicate handlers (which made "connection lost" fire N times).
            pub.unsubscribe(self._on_connection_lost, "meshtastic.connection.lost")
        except Exception:
            pass
        # Close the current interface plus any stale ones from prior drops, cancelling
        # their heartbeat timers (the source of BrokenPipe tracebacks on dead sockets).
        for old in [self._iface, *self._stale_ifaces]:
            if old is not None:
                try:
                    old.close()
                except Exception:
                    pass
        self._stale_ifaces = []
        self._iface = None
        # NOTE: do NOT clear self._host/_port here. They are the *target* config used
        # by _open()/the supervisor to (re)connect. _open() calls _close_locked()
        # before building TCPInterface(self._host, ...), so nulling host here made it
        # connect to None → "Connection refused" forever.

    # ------------------------------------------------------------------

    def is_connected(self) -> bool:
        return self._iface is not None

    def state(self) -> str:
        """Return the three-state connection state.

        `connected` only when there is a live interface. Everything else splits on
        whether we are still usefully trying: `connecting` while the supervisor is
        retrying at full rate below the failure threshold, `disconnected` once the
        user disconnected, the radio library is missing, or N consecutive attempts
        failed and we dropped to the slow retry.
        """
        if self._iface is not None:
            return STATE_CONNECTED
        if not self._want_connected:
            return STATE_DISCONNECTED
        with self._lock:
            if self._hard_error is not None or self._slow_retry:
                return STATE_DISCONNECTED
        return STATE_CONNECTING

    @property
    def iface(self) -> Any:
        if self._iface is None:
            raise RuntimeError("Not connected. Call meshtastic_connect first.")
        return self._iface

    def my_node_id(self) -> str | None:
        return self.local_node_identity()["node_id"]

    def local_node_identity(self) -> dict[str, Any]:
        """Return the connected radio's own Meshtastic identity.

        Meshtastic's TCPInterface exposes the canonical node number via
        ``myInfo.my_node_num``. Human-readable names live in the node DB under
        that node id, so this combines both sources and tolerates either one
        being temporarily absent during startup.
        """
        identity: dict[str, Any] = {
            "node_id": None,
            "true_node_id": None,
            "node_num": None,
            "short_name": None,
            "long_name": None,
        }
        if self._iface is None:
            return identity

        info = getattr(self._iface, "myInfo", None)
        node_num = getattr(info, "my_node_num", None) if info is not None else None
        node_id = None
        if node_num is not None:
            try:
                node_num = int(node_num)
                node_id = f"!{node_num:08x}"
            except Exception:
                node_id = str(node_num)

        nodes = getattr(self._iface, "nodes", None) or {}
        node = nodes.get(node_id, {}) if node_id else {}
        user = node.get("user") or {} if isinstance(node, dict) else {}

        identity.update(
            {
                "node_id": node_id,
                "true_node_id": node_id,
                "node_num": node_num,
                "short_name": user.get("shortName"),
                "long_name": user.get("longName"),
            }
        )
        return identity

    def channel_table(self) -> list[dict[str, Any]]:
        """Return the radio's channel table as normalized rows.

        Rows are ``{"index": int, "name": str, "role": int|None}`` — the shape
        :func:`meshtastic_hermes.gateway_bridge.resolve_channel_spec` consumes. This
        is the ONLY place channel names are read off the radio, which keeps the
        allowlist resolution logic a pure function of this data.

        DISABLED channels (role 0) are omitted: they are empty slots, not channels
        the radio can transmit on. Returns [] when we are not connected.
        """
        iface = self._iface
        if iface is None:
            return []
        local = getattr(iface, "localNode", None)
        channels = getattr(local, "channels", None) or []
        out: list[dict[str, Any]] = []
        for idx, ch in enumerate(channels):
            role = getattr(ch, "role", None)
            if role == 0:  # DISABLED — an empty slot
                continue
            settings = getattr(ch, "settings", None)
            # Prefer the channel's own index when the radio reports one; fall back
            # to position, which is what the index means on the wire.
            index = getattr(ch, "index", None)
            if not isinstance(index, int):
                index = idx
            out.append(
                {
                    "index": index,
                    "name": getattr(settings, "name", "") or "",
                    "role": role,
                }
            )
        return out

    def status(self) -> dict[str, Any]:
        """Connection status.

        ``connected`` is kept as a bool for backwards compatibility and is True
        ONLY for ``state == "connected"`` — while `connecting` there is no usable
        interface, so every existing consumer (adapter health, send path, the
        `iface` property) must keep treating it as not-usable. ``state`` is the new
        three-valued field; ``consecutive_failures`` and ``slow_retry`` expose why.
        """
        state = self.state()
        with self._lock:
            failures = self._consecutive_failures
            slow = self._slow_retry
        return {
            "connected": state == STATE_CONNECTED,
            "state": state,
            "host": self._host,
            "consecutive_failures": failures,
            "slow_retry": slow,
            **self.local_node_identity(),
        }


# Process-wide singletons live in a fixed sys.modules slot (NOT module globals).
# Hermes loads the tools plugin under a mangled package name while the platform
# adapter imports `meshtastic_hermes` as a top-level package (via its sys.path shim),
# so there are TWO copies of this module — each with its own globals. Keying the
# singletons off a fixed sys.modules entry makes both copies share ONE
# ConnectionManager + Observer + KB, i.e. a single radio connection instead of two
# competing ones.
_SHARED_KEY = "meshtastic_hermes._shared_state"


def _shared_state():
    import types

    st = sys.modules.get(_SHARED_KEY)
    if st is None:
        st = types.ModuleType(_SHARED_KEY)
        st.manager = None
        st.observer = None
        sys.modules[_SHARED_KEY] = st
    return st


def get_manager() -> ConnectionManager:
    st = _shared_state()
    if st.manager is None:
        st.manager = ConnectionManager()
    return st.manager
